### ISSUE TITLE
(CaseClauseError) no case clause matching: {"8.8.8.8", 53}

### ISSUE THREAD

**Issue by messutied** [tungd/elixir-dns#17]
Hi, I'm testing the package locally, running `DNS.resolve("google.com")` works but running `DNS.resolve("google.com", {"8.8.8.8", 53})` gives me the following error:

```
** (CaseClauseError) no case clause matching: {"8.8.8.8", 53}
    (kernel) inet_dns.erl:346: :inet_dns.encode_type/1
    (kernel) inet_dns.erl:267: :inet_dns.encode_query_section/3
    (kernel) inet_dns.erl:240: :inet_dns.encode/1
    (dns) lib/dns.ex:46: DNS.query/3
    (dns) lib/dns.ex:15: DNS.resolve/3
```

Any ideas? by the examples in the readme it looks like this should work.
Thanks

**Comment by tungd** [comment]
It looks like there are some change in the `inet_dns` module. What's your version of Erlang, Elixir and `elixir-dns`?

**Comment by messutied** [comment]
Hi @tungd, my Erlang version is `Erlang/OTP 20 [erts-9.3.1]`, `Elixir (1.4.5)` and elixir-dns 2.1.0.
